sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.6
  - ruby-head

services:
  - postgresql
addons:
  postgresql: 9.6

before_install: gem install bundler
before_script:
  - psql -c 'create database scripper_test;' -U postgres
script:
  - bundle exec rspec
  - bundle exec rubocop

cache: bundler
